#!/usr/bin/env python3
"""Regenerate index-replay-preview.html from index.html.

The preview is a GENERATED file — never hand-edit it, edit this script and re-run:

    python3 tools/build-replay-preview.py

index.html is never modified. The preview injects a Wallet Replay entry point plus a bridge
that lets replay-engine.js drive the page's OWN chart and candle series, so the page never
shows a second chart (an earlier iframe version did, and that was the main complaint).
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / 'index.html'
OUT = ROOT / 'index-replay-preview.html'

CSS = """
        /* ===== WALLET REPLAY entry point (PREVIEW — generated, not in index.html) ===== */
        .wr-wrap { padding:10px 12px; border-bottom:1px solid var(--line); display:flex;
                   flex-direction:column; gap:9px; }
        .wr-btn { display:flex; align-items:center; gap:9px; align-self:flex-start; cursor:pointer;
                  font-family:var(--mono); font-size:11.5px; font-weight:800; letter-spacing:.13em;
                  padding:9px 14px; border-radius:9px; background:var(--panel2);
                  border:1px solid var(--line2); color:var(--txt); transition:.15s; }
        .wr-btn:hover { border-color:var(--green-d); color:var(--green); }
        .wr-btn.on { background:var(--green-x); border-color:var(--green-d); color:var(--green);
                     box-shadow:0 0 18px rgba(74,222,128,.22); }
        .wr-btn .c { color:var(--dimmer); transition:.15s; font-size:9px; }
        .wr-btn.on .c { transform:rotate(180deg); color:var(--green); }
        /* while a replay owns the chart the same button is the way out, so it says so */
        .wr-live .wr-btn { background:var(--green-x); border-color:var(--green-d); color:var(--green); }
        .wr-live .wr-btn .c { display:none; }
        .wr-drop { display:none; flex-direction:column; gap:8px; }
        .wr-drop.on { display:flex; animation:wrin .2s ease-out; }
        @keyframes wrin { from{opacity:0;transform:translateY(-6px)} to{opacity:1;transform:none} }
        .wr-row { display:flex; gap:7px; align-items:center; flex-wrap:wrap; }
        .wr-row input { flex:1; min-width:220px; background:var(--bg); border:1px solid var(--line2);
                        border-radius:7px; color:var(--txt); font-family:var(--mono); font-size:12px;
                        padding:10px 12px; outline:none; }
        .wr-row input:focus { border-color:var(--green-d); }
        .wr-row input::placeholder { color:var(--dimmer); }
        .wr-row button { font-family:var(--mono); font-size:10.5px; letter-spacing:.08em; font-weight:700;
                         padding:10px 15px; border-radius:7px; cursor:pointer;
                         background:var(--green-d); border:1px solid var(--green-d); color:#04150c; }
        .wr-row button:hover { background:var(--green); }
        .wr-micro { font-family:var(--mono); font-size:9.5px; color:var(--dimmer); letter-spacing:.05em; }
        .wr-chips { display:flex; gap:6px; flex-wrap:wrap; align-items:center;
                    font-family:var(--mono); font-size:10.5px; }
        .wr-chips .l { color:var(--dimmer); letter-spacing:.1em; }
        .wr-chip { background:var(--panel2); border:1px solid var(--line2); color:var(--dim);
                   padding:5px 10px; border-radius:999px; cursor:pointer; transition:.14s; }
        .wr-chip:hover { border-color:var(--green-d); color:var(--green); }
        .wr-live .chart-bar > * { opacity:.32; pointer-events:none; }
        /* the site's own chart status sits top-left, exactly where the replay HUD does */
        .wr-live .chart-status { display:none; }
"""

HTML = """                <div class="wr-wrap">
                    <div class="wr-btn" id="wrBtn"><span style="font-size:9px">&#9654;</span> <span id="wrLabel">WALLET REPLAY</span> <span class="c">&#9662;</span></div>
                    <div class="wr-drop" id="wrDrop">
                        <div class="wr-row">
                            <input type="text" id="wrAddr" spellcheck="false" autocomplete="off" placeholder="paste a wallet &mdash; Geu1&hellip;aHNc">
                            <button id="wrGo">ENTER</button>
                        </div>
                        <div class="wr-micro">read only &middot; never asks you to connect a wallet or share keys</div>
                        <div class="wr-chips" id="wrChips"></div>
                    </div>
                </div>
"""

JS = r"""
    // ===== WALLET REPLAY (PREVIEW) — drives the SITE'S OWN chart =====
    // Generated by tools/build-replay-preview.py. The first pass embedded replay.html in an
    // iframe, which put two charts on the page; the engine is now handed this page's `chart`
    // and `candleS` and takes them over for the duration.
    //
    // ⚠ The 30s refresh MUST be suspended while a replay runs (see __rpSuspend in refresh()),
    // or a poll lands mid-animation and wipes the series out from under it.
    (function () {
        var $w = function (id) { return document.getElementById(id); };
        var engine = null, savedRange = null, board = [], open = false, live = false;

        async function ensureCandles(firstTs) {
            for (var i = 0; i < 14; i++) {
                if (!base.rows.length) break;
                if (base.rows[0].time * 1000 <= firstTs) break;
                var added = await extendHistory('1h');
                if (!added) break;
            }
            var mult = supply || 1;
            return base.rows.map(function (c) {
                return { time: c.time, open: c.open * mult, high: c.high * mult,
                         low: c.low * mult, close: c.close * mult };
            });
        }

        function begin() {
            live = true;
            window.__rpSuspend = true;
            document.body.classList.add('wr-live');
            $w('wrLabel').textContent = 'EXIT REPLAY';
            $w('wrDrop').classList.remove('on');
            open = false;
            try { savedRange = chart.timeScale().getVisibleLogicalRange(); } catch (e) {}
            lineS.applyOptions({ visible: false });
            volS.applyOptions({ visible: false });
            candleS.applyOptions({ visible: true });
        }
        function end() {
            live = false;
            window.__rpSuspend = false;
            document.body.classList.remove('wr-live');
            $w('wrLabel').textContent = 'WALLET REPLAY';
            applySeries(displayRows());              // the site's own single repaint funnel
            candleS.setMarkers([]);
            lineS.applyOptions({ visible: ctype === 'line' });
            volS.applyOptions({ visible: true });
            candleS.applyOptions({ visible: ctype === 'candle' });
            paintAth();
            if (savedRange) { try { chart.timeScale().setVisibleLogicalRange(savedRange); } catch (e) {} }
            setStatus('');
        }

        function getEngine() {
            if (engine) return engine;
            engine = window.ReplayEngine({
                stage: $w('chartStage'), chart: chart, series: candleS,
                getSupply: function () { return supply || 1; },
                getPrice: function () { return (tok && tok.price) || 0; },
                ensureCandles: ensureCandles,
                nameFor: function (w) { var r = board.filter(function (x) { return x.wallet === w; })[0]; return r && r.name; },
                onStatus: function (s) { setStatus(s); },
                onBegin: begin, onEnd: end,
            });
            return engine;
        }

        function go(w) {
            w = (w || '').trim();
            if (!/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(w)) { $w('wrAddr').focus(); return; }
            getEngine().play(w);
        }
        async function submit() {
            var v = $w('wrAddr').value.trim();
            if (!v) { try { v = ((await navigator.clipboard.readText()) || '').trim(); if (v) $w('wrAddr').value = v; } catch (e) {} }
            if (!v) { $w('wrAddr').focus(); return; }
            go(v);
        }

        // One control, three states: closed -> open the drawer, open -> close it, playing -> exit.
        // A separate EXIT button was a second thing to find for an action the same button implies.
        $w('wrBtn').onclick = function () {
            if (live) { if (engine) engine.close(); return; }
            open = !open;
            $w('wrDrop').classList.toggle('on', open);
            $w('wrBtn').classList.toggle('on', open);
            if (open) $w('wrAddr').focus();
        };
        $w('wrGo').onclick = submit;
        $w('wrAddr').onkeydown = function (e) { if (e.key === 'Enter') submit(); };
        document.addEventListener('keydown', function (e) { if (e.key === 'Escape' && live && engine) engine.close(); });

        fetch('holders/traders.json').then(function (r) { return r.json(); }).then(function (b) {
            board = b.traders || [];
            var rows = board.filter(function (r) { return !r.partial && !r.capped; }).slice(0, 3);
            if (!rows.length) return;
            var fmtK = function (v) { var a = Math.abs(v); return (v < 0 ? '-' : '+') + '$' +
                (a >= 1e6 ? (a/1e6).toFixed(1) + 'M' : a >= 1e3 ? (a/1e3).toFixed(1) + 'K' : a.toFixed(0)); };
            var sh = function (a) { return a.slice(0, 4) + '…' + a.slice(-4); };
            $w('wrChips').innerHTML = '<span class="l">OR WATCH</span>' + rows.map(function (r) {
                return '<span class="wr-chip" data-w="' + r.wallet + '">' + (r.name || sh(r.wallet)) + ' ' + fmtK(r.total) + '</span>';
            }).join('') + '<span class="wr-chip" data-rand="1">🎲 RANDOM</span>';
            Array.prototype.forEach.call($w('wrChips').querySelectorAll('.wr-chip'), function (el) {
                el.onclick = function () {
                    var w = el.dataset.rand ? board[Math.floor(Math.random() * Math.min(board.length, 40))].wallet : el.dataset.w;
                    $w('wrAddr').value = w; go(w);
                };
            });
        }).catch(function () {});
    })();
"""

def build():
    src = SRC.read_text()
    out = src

    anchors = [
        ("        .chart-stage { position:relative; }", 'chart-stage css anchor'),
        ('                <div class="chart-stage" id="chartStage">', 'chart stage markup anchor'),
        ('<script src="lightweight-charts.js?v=421"></script>', 'lightweight-charts script tag'),
        ("if (document.hidden) return;          // but skip the chart work while hidden\n            await refreshCandles();", 'refresh suspend anchor'),
    ]
    for a, why in anchors:
        if a not in out:
            sys.exit('ANCHOR MISSING (%s) — index.html changed shape; update this script.' % why)

    out = out.replace(anchors[0][0], anchors[0][0] + "\n" + CSS, 1)
    out = out.replace(anchors[1][0], HTML + anchors[1][0], 1)
    out = out.replace(anchors[2][0],
        anchors[2][0] + '\n    <script src="tools/pnl.js?v=1"></script>\n    <script src="replay-engine.js?v=2"></script>', 1)
    out = out.replace(anchors[3][0],
        "if (document.hidden) return;          // but skip the chart work while hidden\n"
        "            if (window.__rpSuspend) return;       // a replay owns the chart right now\n"
        "            await refreshCandles();", 1)

    i = out.rindex('</script>')
    out = out[:i] + JS + "\n" + out[i:]
    OUT.write_text(out)
    print('wrote %s (%d lines)' % (OUT.name, len(out.splitlines())))

if __name__ == '__main__':
    build()
